spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  error:
    include-stacktrace: never

